spring:
  application:
    name: Tlias-smart- learning-assistant-system
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  web:
    resources:
      static-locations:
      - classpath:/static/
      - file:C:/Source Code/Java/Web/Tlias-smart-learning-assistant-system/upload/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# MyBatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
# 配置事务管理日志级别
logging:
    level:    
      '[org.springframework.jdbc.support.JdbcTransactionManager]': debug

prop:
  upload-folder: C:/Source Code/Java/Web/Tlias-smart-learning-assistant-system/upload/
  download-folder: http://localhost:8080/