spring:
  application:
    name: Tlias-smart- learning-assistant-system
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

# MyBatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
# 配置事务管理日志级别
logging:
    level:    
      '[org.springframework.jdbc.support.JdbcTransactionManager]': debug